source 'https://github.com/CocoaPods/Specs'

platform :ios, '8.0'

use_frameworks!

xcodeproj 'YSRangeSliderExample'
workspace '../YSRangeSlider'

target :YSRangeSliderExample do
  pod 'YSRangeSlider', :path => '../'
end